### ISSUE TITLE
You can pass through the world border as Mario

### ISSUE THREAD

**Issue by GitHubEnjoyerr** [Retro64Mod/Retro64Mod#9]

**Comment by dylanpdx** [comment]
Probably the same issue as https://github.com/Retro64Mod/Retro64Mod.github.io/issues/11

**Comment by dylanpdx** [comment]
Fixed in https://github.com/Retro64Mod/Retro64Mod/commit/9c2d4d2d3788b769830ab0e2d621f6ec878f244b
